const AccessControl = require('accesscontrol')
const ac = new AccessControl()
ac.grant('user')
  .createOwn('post')
  .deleteOwn('post')
  .updateOwn('post')
  .readAny('post')
  .createOwn('comment')
  .deleteOwn('comment')
  .updateOwn('comment')
  .readAny('comment')
.grant('admin')
  .extend('user')
  .updateAny('post')
  .deleteAny('post')
  .updateAny('comment')
  .deleteAny('comment')

module.exports = ac